version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 16
    commands:
      - npm install
  pre_build:
    commands:
      - yarn && yarn preprocess
  build:
    commands:
      - cd localfork
      - yarn install
      - node ForkSetup.js -l
      - node ForkSetup.js -d
      - node ForkSetup.js -dp
      - SCRIPT=$(node ForkSetup.js -b)
      - echo $SCRIPT
      - cd ..
artifacts:
  files:
    - '**/*'